name: Lint Markdown

on:
  push:
  pull_request:

jobs:
  lint:
    name: Run Markdown Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Run markdownlint-cli2
        run: bunx markdownlint-cli2 "**/*.md" "#node_modules"
